#!/usr/bin/env sh

# Shell script to install winbox on GNU/Linux (wine).
# Author: owl4ce
# License: GPL-3.0
# ---------------------------------
# https://github.com/owl4ce/winebox

LC_ALL=C LANG=C; # Speedup script by disable unicode.
R="\033[1;31m" M="\033[1;35m" G="\033[1;32m" W="\033[1;37m" NC="\033[0m"

# Output messages.
err() { printf "${R} > error:${NC} $*\n"; exit 1; }
msg() { printf "${G} > ${NC}$*\n"; }

# Check dependencies.
checkdep() { type "$1" >/dev/null 2>&1 || err "${M}$1${NC} is not installed. Please install it first!"; }

# Winbox (64/32)-bit.
winbox32() { curl -L "https://mt.lv/winbox" -o "${HOME}/.winebox/winbox32.exe"; }
winbox64() { curl -L "https://mt.lv/winbox64" -o "${HOME}/.winebox/winbox64.exe"; }

# Get OS's arch.
CHK_ARCH="$(lscpu | grep -oP 'Architecture:.*_\K[^.*]+')"

install() {
    # Check all dependencies.
    for X in "lscpu" "curl" "wine"; do checkdep "$X"; done && unset X
    
    # Inform wine version and OS's arch.
    msg "Wine: $(wine --version 2>/dev/null)"
    msg "Arch: ${CHK_ARCH}-bit"
    
    # Create the winebox dir, then download the winebox logo.
    [ ! -d "${HOME}/.winebox" ] && mkdir -p "${HOME}/.winebox" || :
    curl -sL -o "${HOME}/.winebox/winebox.png" \
    "https://raw.githubusercontent.com/owl4ce/winebox/main/.winebox/winebox.png" 
    
    # Download winbox.
    if [ ! -f "${HOME}/.winebox/winbox${CHK_ARCH}.exe" ]; then
        msg "Downloading Winbox ${M}[${NC}${CHK_ARCH}-bit${M}]${NC}"
        winbox${CHK_ARCH} 2>/dev/null
    else
        err "Winebox already exist. Exiting .."; exit 1
    fi
    
    # Create a desktop shortcut.
    msg "Creating desktop shortcut .. "
    [ ! -d "${HOME}/.local/share/applications" ] && \
    mkdir -p "${HOME}/.local/share/applications"
    
    [ "$CHK_ARCH" = "32" ] && wine="wine" || wine="wine64"
    cat > "${HOME}/.local/share/applications/winebox.desktop" << EOF
[Desktop Entry]
Comment=Run MikroTik Winbox over Wine (${CHK_ARCH}-bit)
Terminal=false
Name=Winebox
Categories=Network;
GenericName=MikroTik Utility
Exec=${wine} ${HOME}/.winebox/winbox${CHK_ARCH}.exe
Type=Application
Icon=${HOME}/.winebox/winebox.png
EOF

    # Make sure the desktop shortcut is executable.
    chmod +x "${HOME}/.local/share/applications/winebox.desktop"
    msg "Winebox successfully installed!" # Success.
}

if [ "$(id -u)" -eq 0 ]; then    
    err "Running as ${R}root${NC} is detected. Please run as regular user!"; exit 1
else
    case ${1} in
        -u) if [ -d "${HOME}/.winebox" ]; then
                rm -rfv "${HOME}/.winebox" "${HOME}/.local/share/applications/winebox.desktop" && \
                msg "Winebox successfuly removed!"
            else
                err "Winebox not installed!"
            fi
        ;;
        -*) err "unknown option (${1})"
        ;;
        *)  install
        ;;
    esac
fi
